CREATE TABLE tb_previsao(
	cod_previsao INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	--varchar: padrão ANSI
	--varchar2: padrão especifico ORACLE (otimizado)
	cidade VARCHAR2(500),
	data_previsao TIMESTAMP,
	link_previsao VARCHAR2(500)
); 
  
INSERT INTO tb_previsao(
	cidade, data_previsao, link_previsao) values ('itu', CURRENT_TIMESTAMP, 'http://teste.com.br');
);
